name: Deploy to Vercel Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Production
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_MGLKh5XmYFCwtCh6CjyaaL6f
          VERCEL_PROJECT_ID: prj_BjUvWyOuoXPu3FQ72xvFGhYI0LWp
